[package]
name = "scrypto-test"
version = "0.12.0"
edition = "2021"

[dependencies]
# The Radix Engine Stack
sbor = { path = "../sbor" }
transaction = { path = "../transaction" }
radix-engine = { path = "../radix-engine" }
radix-engine-stores = { path = "../radix-engine-stores" }
radix-engine-common = { path = "../radix-engine-common" }
radix-engine-interface = { path = "../radix-engine-interface" }
radix-engine-store-interface = { path = "../radix-engine-store-interface" }

# A library used to allow for self-referencing structs in Rust. This is used in the TestRuntime's 
# internal implementation to have do self-referencing.
ouroboros = { version = "0.17.2" }

# A library used for more powerful declarative macros.
paste = { version = "1.0.14" }