[package]
name = "radiswap"
version = "1.2.0-dev"
edition = "2021"

[dependencies]
sbor = { path = "../../../sbor" }
scrypto = { path = "../../../scrypto" }

[dev-dependencies]
radiswap = { path = ".", features = ["test"] }
native-sdk = { path = "../../../native-sdk" }
transaction = { path = "../../../transaction" }
radix-engine = { path = "../../../radix-engine" }
scrypto-test = { path = "../../../scrypto-test" }

[features]
default = []
test = []

[lib]
doctest = false
crate-type = ["cdylib", "lib"]