[package]
name = "radiswap"
version = "1.2.0-dev"
edition = "2021"

[dependencies]
sbor = { path = "../../../sbor" }
scrypto = { path = "../../../scrypto" }

[dev-dependencies]
scrypto-test = { path = "../../../scrypto-test" }
radix-engine = { path = "../../../radix-engine" }
radix-common = { path = "../../../radix-common" }
radix-native-sdk = { path = "../../../radix-native-sdk" }
radix-engine-interface = { path = "../../../radix-engine-interface" }

[features]
default = []

[lib]
doctest = false
crate-type = ["cdylib", "lib"]