[package]
name = "radix-clis-common"
version = "1.2.0-dev"
edition = "2021"
description = "Shared logic of the Radix CLIs."
readme = "README.md"
license-file = "../LICENSE"
repository = "https://github.com/radixdlt/radixdlt-scrypto"

[dependencies]
