[workspace]
# It's its own workspace - hide it from the root workspace

[package]
name = "simulator"
version = "1.0.0-dev"
edition = "2021"

[dependencies]
sbor = { path = "../sbor" }
radix-engine = { path = "../radix-engine" }
radix-engine-store-interface = { path = "../radix-engine-store-interface" }
radix-engine-stores = { path = "../radix-engine-stores", features = ["rocksdb"] }
radix-engine-queries = { path = "../radix-engine-queries" }
radix-engine-interface = { path = "../radix-engine-interface" }
transaction = { path = "../transaction" }
utils = { path = "../utils" }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = { version = "1.0.81" }
clap = { version = "3.1.17", features = ["derive", "cargo"] }
dirs = { version = "4.0.0" }
colored = { version = "2.0.0" }
hex = { version = "0.4.3" }
cargo_toml = { version = "0.11.5" }
rand = { version = "0.8.5" }
regex = { version = "1.5.5" }
temp-env = { version = "0.2.0" }
wasm-opt = { version = "0.114.1" }
syn = { git = "https://github.com/dtolnay/syn.git", tag = "1.0.93", features = ["full", "extra-traits"] }
quote = { version = "1.0.18" }
proc-macro2 = { version = "1.0.38" }
heck = "0.4.1"

[[bin]]
name = "resim"
path = "src/bin/resim.rs"
bench = false

[[bin]]
name = "scrypto"
path = "src/bin/scrypto.rs"
bench = false

[[bin]]
name = "rtmc"
path = "src/bin/rtmc.rs"
bench = false

[[bin]]
name = "rtmd"
path = "src/bin/rtmd.rs"
bench = false

[[bin]]
name = "scrypto-bindgen"
path = "src/bin/scrypto_bindgen.rs"
bench = false

[lib]
doctest = false
bench = false
