[package]
name = "substate-stores-interface"
version = "1.2.0-dev"
edition = "2021"

[dependencies]
utils = { path = "../utils", default-features = false }
sbor = { path = "../sbor", default-features = false }
radix-engine-common = { path = "../radix-engine-common", default-features = false }

# External dependencies
itertools = { version = "0.10.3", default-features = false }
hex = { version = "0.4.3", default-features = false }

[features]
default = ["std"]
std = ["hex/std", "utils/std", "sbor/std", "radix-engine-common/std", "itertools/use_std"]
alloc = ["hex/alloc", "utils/alloc", "sbor/alloc", "radix-engine-common/alloc", "itertools/use_alloc"]


# Ref: https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
doctest = false
bench = false
