[package]
name = "transaction-scenarios"
version = "1.2.0-dev"
edition = "2021"

[dependencies]
sbor = { path = "../sbor", default-features = false }
radix-engine = { path = "../radix-engine", default-features = false }
substate-stores = { path = "../substate-stores", default-features = false }
substate-stores-interface = { path = "../substate-stores-interface", default-features = false }
radix-engine-system-interface = { path = "../radix-engine-system-interface", default-features = false }
scrypto = { path = "../scrypto", default-features = false }
transaction = { path = "../transaction", default-features = false }
utils = { path = "../utils", default-features = false }
itertools = { version = "0.10.3", default-features = false }
hex = { version = "0.4.3", default-features = false }
walkdir = "2.3.3"

[features]
# You should enable either `std` or `alloc`
default = ["std"]
std = ["hex/std", "sbor/std", "scrypto/std", "transaction/std", "radix-engine/std", "radix-engine/moka", "substate-stores/std", "radix-engine-system-interface/std", "substate-stores-interface/std", "utils/std"]
alloc = ["hex/alloc", "sbor/alloc", "scrypto/alloc", "transaction/alloc", "radix-engine/alloc", "radix-engine/lru", "substate-stores/alloc", "radix-engine-system-interface/alloc", "substate-stores-interface/alloc", "utils/alloc"]

# Ref: https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
doctest = false
bench = false
