[package]
name = "radix-engine-interface"
version = "0.8.0"
edition = "2021"

[dependencies]
sha2 = { version = "0.10.6", default-features = false }
sha3 = { version = "0.10.6", default-features = false }
hex = { version = "0.4.3", default-features = false }
num-traits = { version = "0.2.15", default-features = false }
num-integer = { version = "0.1.45", default-features = false }
num-bigint = { version = "0.4.3", default-features = false }
bech32 = { version = "0.9.0", default-features = false }
sbor = { path = "../sbor", default-features = false }
radix-engine-derive = { path = "../radix-engine-derive", default-features = false }
scrypto-abi = { path = "../scrypto-abi", default-features = false }
utils = { path = "../utils", default-features = false }
paste = { version = "1.0.7"}
serde = { version = "1.0.144", default-features = false, optional = true }
serde_with = { version = "2.0.1", optional = true }
strum = { version = "0.24", default-features = false, features = ["derive"] }
bnum = { version = "0.4.0", default-features = false, features = ["numtraits"] }
blake2 = { version = "0.10.6" }

[dev-dependencies]
serde_json = { version = "1.0.81", default-features = false }
criterion = { version = "0.3", features = ["html_reports"] }
# This is for math benchmarks for comparison purposes.
# Fast alternative to bigint but unfortunately not cross-compiled to WASM
rug = { version = "1.18" }
num-integer = { version = "0.1.45", default-features = false }
ethnum = {version = "1.3.2", default-features = false }

# hash algoriths for benchmarks
blake3 = { version = "1.3.3" }
webb-pedersen-hash = { version = "0.1.0" }
dusk-poseidon = { version = "0.28.1" }
dusk-bls12_381 = { version = "0.11.2" }
dusk-bytes = { version = "0.1.6" }
k12 = { version = "0.2.1" }

[[bench]]
name = "math"
harness = false

[[bench]]
name = "hash"
harness = false

[features]
# You should enable either `std` or `alloc`
default = ["std"]
std = ["hex/std", "sbor/std", "scrypto-abi/std", "radix-engine-derive/std", "strum/std", "utils/std", "serde_json/std"]
alloc = ["hex/alloc", "sbor/alloc", "scrypto-abi/alloc", "radix-engine-derive/alloc", "utils/alloc", "serde_json/alloc"]

# Turn on this feature to enable tracing.
trace = ["radix-engine-derive/trace"]

# Enable serde derives
serde = ["utils/serde", "sbor/serde", "scrypto-abi/serde", "serde/derive", "hex/serde", "serde_with"]

