[package]
name = "rust-analyzer-tests"
version = "1.2.0-dev"
edition = "2021"
description = "A crate with integration tests and benchmarks for Scrypto and Rust Analyzer."
readme = "README.md"
license-file = "../LICENSE"
repository = "https://github.com/radixdlt/radixdlt-scrypto"

[dependencies]
radix-clis-common = { workspace = true }
serde_json = { workspace = true }
regex = { workspace = true }
tempfile = { version = "3.8.0" }

# The following must all match the versions used by Rust Analyzer itself. Otherwise you might run
# into type errors. 
rust-analyzer = { git = "https://github.com/rust-lang/rust-analyzer", tag = "2024-04-01" }
paths = { git = "https://github.com/rust-lang/rust-analyzer", tag = "2024-04-01" }
lsp-server = { version = "0.7.6" }
lsp-types = { version = "=0.95.0", features = ["proposed"] }
crossbeam-channel = { version = "0.5.5" }
url = { version = "2.0.0", features = ["serde"] }
tracing-subscriber = { version = "0.3.18", default-features = false, features = [
    "registry",
    "fmt",
    "tracing-log",
] }
