[package]
name = "scrypto-derive-tests"
version = "1.2.0-dev"
edition = "2021"

[dev-dependencies]
scrypto = { workspace = true }
radix-rust = { workspace = true }
sbor = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bech32 = { workspace = true }

[features]
default = ["std"]
std = ["serde/std", "serde_json/std", "scrypto/std", "scrypto/serde", "sbor/std", "radix-rust/std"]
alloc = ["serde/alloc", "serde_json/alloc", "scrypto/alloc", "scrypto/serde", "sbor/alloc", "radix-rust/std"]
