[package]
name = "faucet"
version = "1.0.0"
edition = "2021"

[dependencies]
sbor = { path = "../../../sbor" }
scrypto = { path = "../../../scrypto" }

[lib]
doctest = false
crate-type = ["cdylib", "lib"]