[package]
name = "genesis-helper"
version = "1.0.0"
edition = "2021"

[dependencies]
sbor = { path = "../../../../sbor" }
scrypto = { path = "../../../../scrypto" }
radix-rust = { path = "../../../../radix-rust" }

[lib]
doctest = false
crate-type = ["cdylib", "lib"]
