[package]
name = "radix-engine-profiling"
version = "1.2.0-dev"
edition = "2021"

[dependencies]
substate-stores-interface = { path = "../substate-stores-interface", default-features = false, optional = true }
substate-stores = { path = "../substate-stores", default-features = false, optional = true }
radix-engine-system-api = { path = "../radix-engine-system-api", default-features = false, optional = true }
fixedstr = "0.2.9"
shared_memory = { version = "0.12.4", optional = true }
plotters = { version = "0.3.4", optional = true }
linreg = { version = "0.2.0", optional = true }
blake2 = { version = "0.10.6", default-features = false, optional = true }
rand = { version = "0.8.5", optional = true }

[lib]
doctest = false
bench = false

[features]
default = []
resource_tracker = ["dep:shared_memory"]
rocksdb = ["dep:plotters", "dep:linreg", "dep:blake2", "dep:rand", "substate-stores/std", 
           "substate-stores-interface/std", "radix-engine-system-api/std"]
ram_metrics = []
