[package]
name = "substate-stores-queries"
version = "1.2.0-dev"
edition = "2021"

[dependencies]
utils = { path = "../utils", default-features = false }
sbor = { path = "../sbor", default-features = false }
radix-engine-common = { path = "../radix-engine-common", default-features = false }
substate-stores-interface = { path = "../substate-stores-interface", default-features = false }

# External dependencies
itertools = { version = "0.10.3", default-features = false }
hex = { version = "0.4.3", default-features = false }
paste = { version = "1.0.13" }

[features]
# You should enable either `std` or `alloc`
default = ["std"]
std = ["hex/std", "sbor/std", "radix-engine-common/std", "substate-stores-interface/std", "utils/std"]
alloc = ["hex/alloc", "sbor/alloc", "radix-engine-common/alloc", "substate-stores-interface/alloc", "utils/alloc"]

# Ref: https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
doctest = false
bench = false
