[package]
name = "substate-stores-queries"
version = "1.2.0-dev"
edition = "2021"

[dependencies]
sbor = { path = "../sbor", default-features = false }
radix-engine = { path = "../radix-engine", default-features = false }
substate-stores-interface = { path = "../substate-stores-interface", default-features = false }
radix-engine-system-api = { path = "../radix-engine-system-api", default-features = false }
transaction = { path = "../transaction", default-features = false }
utils = { path = "../utils", default-features = false }
itertools = { version = "0.10.3", default-features = false }
hex = { version = "0.4.3", default-features = false }
paste = { version = "1.0.13" }

[features]
# You should enable either `std` or `alloc`
default = ["std", "moka"]
std = ["radix-engine/std", "hex/std", "sbor/std", "transaction/std", "radix-engine-system-api/std", "substate-stores-interface/std", "utils/std"]
alloc = ["radix-engine/alloc", "hex/alloc", "sbor/alloc", "transaction/alloc", "radix-engine-system-api/alloc", "substate-stores-interface/alloc", "utils/alloc"]

moka = ["radix-engine/moka"]
lru = ["radix-engine/lru"]

# Ref: https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
doctest = false
bench = false
