[package]
name = "transaction"
version = "0.7.0"
edition = "2021"

[dependencies]
sbor = { path = "../sbor", default-features = false }
radix-engine-interface = { path = "../radix-engine-interface", default-features = false }
scrypto = { path = "../scrypto", default-features = false }
utils = { path = "../utils", default-features = false }
clap = { version = "3.1.17", features = ["derive", "cargo"] }
hex = { version = "0.4.3", default-features = false }
ed25519-dalek = { version = "1.0.1", default-features = false, features = ["u64_backend"]}
secp256k1 = { version = "0.24.0", default-features = false, features = ["global-context", "recovery"]}
serde = { version = "1.0.144", default-features = false, optional = true }
serde_with = { version = "2.0.1" }

[features]
# You should enable either `std` or `alloc`
default = ["std"]
std = ["sbor/std", "radix-engine-interface/std", "scrypto/std", "hex/std", "ed25519-dalek/std", "secp256k1/std", "utils/std"]
alloc = ["sbor/alloc", "radix-engine-interface/alloc", "scrypto/alloc", "hex/alloc", "ed25519-dalek/alloc", "secp256k1/alloc", "utils/alloc"]
serde = ["serde/derive", "scrypto/serde"]