[package]
name = "transaction"
version = "1.2.0-dev"
edition = "2021"

[dependencies]
utils = { path = "../utils", default-features = false }
sbor = { path = "../sbor", default-features = false }
radix-engine-common = { path = "../radix-engine-common", default-features = false, features = ["secp256k1_sign_and_validate"] }
native-blueprints-interface = { path = "../native-blueprints-interface", default-features = false }
module-blueprints-interface = { path = "../module-blueprints-interface", default-features = false }

# External dependencies
hex = { version = "0.4.3", default-features = false }
serde = { version = "1.0.144", default-features = false, optional = true }
lazy_static = "1.4.0"
strum = { version = "0.24", default-features = false, features = ["derive"] }
bech32 = { version = "0.9.0", default-features = false }

[dev-dependencies]
scrypto = { path = "../scrypto" }
scrypto-derive = { path = "../scrypto-derive" }
blueprint-schema = { path = "../blueprint-schema" }

[features]
# You should enable either `std` or `alloc`
default = ["std"]
std = ["sbor/std", "utils/std", "radix-engine-common/std", "hex/std"]
alloc = ["sbor/alloc", "utils/alloc", "radix-engine-common/alloc", "hex/alloc", "lazy_static/spin_no_std"]
serde = ["serde/derive"]

dump_manifest_to_file = []

# This flag is set by fuzz-tests framework
radix_engine_fuzzing = [
    "sbor/radix_engine_fuzzing",
    "utils/radix_engine_fuzzing",
    "radix-engine-common/radix_engine_fuzzing",
]

[lib]
doctest = false
bench = false
