[package]
name = "sbor-derive"
version = "1.2.0-dev"
edition = "2021"
description = "A collection of macros for deriving SBOR implementations, from the Radix DLT project."
readme = "README.md"
license-file = "../LICENSE"
repository = "https://github.com/radixdlt/radixdlt-scrypto"

[lib]
doctest = false
proc-macro = true
bench = false

[dependencies]
proc-macro2 = { workspace = true }
sbor-derive-common = { workspace = true }

[features]
trace = ["sbor-derive-common/trace"]
