[package]
name = "core"
version = "1.2.0-dev"
edition = "2021"

[dependencies]
sbor = { path = "../../../../sbor" }
scrypto = { path = "../../../../scrypto" }
radix-rust = { path = "../../../../radix-rust" }

[dev-dependencies]
radix-engine = { path = "../../../../radix-engine" }

[lib]
doctest = false
crate-type = ["cdylib", "lib"]