name: Build scrypto-builder image

on:
  push:
    branches:
      - chore/avoid-builder-push
      - develop
      - main
      - release\/*

jobs:
  tags:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.setup_tags.outputs.tag }}
    steps:
      - uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 0
      - id: setup_tags
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
  build-amd:
    needs: tags
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/docker-build.yml@chore/conditionaly-push
    with:
      runs_on: ubuntu-latest-16-cores
      image_registry: "docker.io"
      image_organization: "radixdlt"
      image_name: "scrypto-builder"
      tag: ${{ needs.tags.outputs.tag }}
      context: "."
      dockerfile: "Dockerfile"
      platforms: "linux/amd64"
      provenance: "false"
      scan_image: false
      snyk_target_ref: ${{ github.ref_name }}
      enable_dockerhub: false
      push_image: false
      post_script: "./update-assets.sh --reuse-image --image-tag ${{ needs.tags.outputs.tag }}"
    secrets:
      workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
      service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      role_to_assume: ${{ secrets.DOCKERHUB_RELEASER_ROLE }}

