name: CI

on:
  push:
    branches:

env:
  CARGO_TERM_COLOR: always

jobs:
  radix-engine:
    name: Run Radix Engine tests
    runs-on: k8s-linux-runner
    steps:
      - uses: actions/checkout@v3
      - uses: radixdlt/public-iac-resuable-artifacts/rust-setup@chore/install-dependencia-action
      - uses: radixdlt/public-iac-resuable-artifacts/rust-coverage@chore/install-dependencia-action
        with:
          flags: -p radix-engine-common -p radix-engine-derive -p radix-engine-interface -p radix-engine -p radix-engine-tests --features compile-blueprints-at-build-time post_run_db_check
  sbor-unit-tests:
    name: Run SBOR unit tests
    runs-on: ${{ matrix.os }}
    env:
      CARGO_LOG: info
    strategy:
      matrix:
        os: [k8s-linux-runner]
    steps:
      - uses: actions/checkout@v3
      - uses: radixdlt/public-iac-resuable-artifacts/rust-setup@chore/install-dependencia-action
      - uses: radixdlt/public-iac-resuable-artifacts/rust-coverage@chore/install-dependencia-action
        with:
          flags: -p sbor
      - uses: radixdlt/public-iac-resuable-artifacts/rust-coverage@chore/install-dependencia-action
        with:
          flags: -p sbor --no-default-features --features alloc
      - uses: radixdlt/public-iac-resuable-artifacts/rust-coverage@chore/install-dependencia-action
        with:
          flags: -p sbor-derive-common
