name: CI

on:
  push:
    branches:
      - main
      - develop
      - docs
      - alphanet
      - betanet
      - release\/*
  pull_request:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-code-format:
    name: Check code format
    runs-on: ubuntu-latest
    container:
      image: rust:1.70.0-bullseye
    env:
      CARGO_LOG: info
    steps:
    - uses: actions/checkout@v3
    - name: Check format
      run: |
        rustup component add rustfmt
        bash ./check.sh

  sbor-unit-tests:
    name: Run SBOR unit tests
    runs-on: ubuntu-latest
    container:
      image: rust:1.70.0-bullseye
    env:
      CARGO_LOG: info
    steps:
      - uses: actions/checkout@v3
      - name: setup the container
        run: |
          apt update && apt install -y clang llvm cmake build-essential
          rustup component add llvm-tools
          cargo install cargo-llvm-cov cargo-nextest
      - uses: radixdlt/public-iac-resuable-artifacts/rust-coverage@main
        with:
          flags: -p sbor
          coverage_report_name: sbor-coverage
      - uses: radixdlt/public-iac-resuable-artifacts/rust-coverage@main
        with:
          flags: -p sbor --no-default-features --features alloc
          coverage_report_name: sbor-coverage
      - uses: radixdlt/public-iac-resuable-artifacts/rust-coverage@main
        with:
          flags: -p sbor-derive-common
          coverage_report_name: sbor-derive-common-coverage

  sbor-integration-tests:
    name: Run SBOR integration tests
    runs-on: ubuntu-latest
    container:
      image: rust:1.70.0-bullseye
    env:
      CARGO_LOG: info
    steps:
      - uses: actions/checkout@v3
      - name: setup the container
        run: |
          apt update && apt install -y clang llvm cmake build-essential
          rustup component add llvm-tools
          cargo install cargo-llvm-cov cargo-nextest
      - uses: radixdlt/public-iac-resuable-artifacts/rust-coverage@main
        with:
          flags: -p sbor-tests
          coverage_report_name: sbor-tests-coverage
      - uses: radixdlt/public-iac-resuable-artifacts/rust-coverage@main
        with:
          flags: -p sbor-tests --no-default-features --features alloc
          coverage_report_name: sbor-tests-coverage
      - name: Run bench
        run: cargo bench
        working-directory: sbor-tests

  scrypto-unit-tests:
    name: Run Scrypto unit tests
    runs-on: ubuntu-latest
    container:
      image: rust:1.70.0-bullseye
    env:
      CARGO_LOG: info
    steps:
    - uses: actions/checkout@v3
    - name: setup the container
        run: |
          apt update && apt install -y clang llvm cmake build-essential
          rustup component add llvm-tools
          cargo install cargo-llvm-cov cargo-nextest
    - uses: radixdlt/public-iac-resuable-artifacts/rust-coverage@main
      with:
        tests-dir: scrypto
        flags: -p scrypto
        coverage_report_name: scrypto-coverage
    - uses: radixdlt/public-iac-resuable-artifacts/rust-coverage@main
      with:
        flags: -p scrypto --no-default-features --features alloc
        coverage_report_name: scrypto-coverage
    - uses: radixdlt/public-iac-resuable-artifacts/rust-coverage@main
      with:
        flags: -p scrypto-schema
        coverage_report_name: scrypto-schema-coverage
    - uses: radixdlt/public-iac-resuable-artifacts/rust-coverage@main
      with:
        flags: scrypto-derive
        coverage_report_name: scrypto-derive-coverage
  
  scrypto-integration-tests:
    name: Run Scrypto integration tests
    runs-on: ubuntu-latest
    container:
      image: rust:1.70.0-bullseye
    env:
      CARGO_LOG: info
    steps:
    - uses: actions/checkout@v3
    - name: setup the container
        run: |
          apt update && apt install -y clang llvm cmake build-essential
          rustup component add llvm-tools
          cargo install cargo-llvm-cov cargo-nextest
    - uses: radixdlt/public-iac-resuable-artifacts/rust-coverage@main
      with:
        flags: -p scrypto-derive-tests
        coverage_report_name: scrypto-derive-tests-coverage
    - uses: radixdlt/public-iac-resuable-artifacts/rust-coverage@main
      with:
        flags: -p scrypto-derive-tests --no-default-features --features alloc
        coverage_report_name: scrypto-derive-tests-coverage
  
