name: Simulator

on:
  push:
    branches:
      - chore/simulator-image

jobs:
  build-simulator-arm:
    runs-on: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./simulator/Dockerfile

  build-simulator-amd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./simulator/Dockerfile

  update-assets-amd:
    needs: build-simulator-amd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update assets
        run: ./update-assets-docker.sh

  update-assets-arm:
    needs: build-simulator-arm
    runs-on: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update assets
        run: ./update-assets-docker.sh
