name: Simulator

on:
  push:
    branches:
      - chore/simulator-image

jobs:
  build-simulator-arm:
    runs-on: arm64
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./simulator/Dockerfile

  build-simulator-amd:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./simulator/Dockerfile
